### PR TITLE
use callback to fix issue 

### LINKED ISSUE #1: UseEffect warning at HomePage for getData()

### PR DESCRIPTION
**Pull request by krystalmai**
WHY: The getData() function was used both inside (line98) and outside (line 116) the useeffect scope, but the dependency array contained "page" which caused a "missing dependency" warning. But getData() was defined outside so adding getData() to the array will cause this warning:

`the 'getData' function makes the dependencies of useEffect Hook (at line 99) change on every render. To fix this, wrap the definition of 'getData' in its own useCallback() Hook  react-hooks/exhaustive-deps`

So I used useCallback() hook to memorize the function and resolve the above warning

### CODE REVIEW

File: src/components/FormModal.js [hunk 1]
```diff
@@ -67,7 +67,7 @@ export default function FormModal({ open, handleClose, mode, selectedCar, modalK
 			setErrors({});
 			setForm(selectedCar);
 		} else setForm(initial_form);
-	}, [selectedCar?._id]);
+	}, [selectedCar]);
 	console.log('render');
```
Comment (eatmoarrice) [inline src/components/FormModal.js]: Delete this line.

File: src/pages/HomePage.js [hunk 2]
```diff
@@ -1,130 +1,155 @@
...
-				/>
-			</div>
-			<Fab variant="extended" color="info" onClick={handleClickNew} sx={{ position: 'fixed', bottom: 10, left: 10 }} aria-label="add">
-				<AddIcon />
-				New
-			</Fab>
-		</Container>
-	);
-};
+  const getData = useCallback(async () => {
```
Comment (eatmoarrice) [inline src/pages/HomePage.js]: https://reactjs.org/docs/hooks-faq.html#is-it-safe-to-omit-functions-from-the-list-of-dependencies

**The recommended fix is to move that function inside of your effect.**

Do something like this: 
image

`useCallback` hook is a last resort, so let's avoid this.

File: src/pages/HomePage.js [hunk 3]
```diff
@@ -1,130 +1,155 @@
...
+    const res = await apiService.get(`/cars?page=${page}`);
+    console.log(res.data.cars[0]);
```
Comment (eatmoarrice) [inline src/pages/HomePage.js]: Delete this.

File: src/components/FormModal.js [hunk 4]
```diff
@@ -34,7 +34,7 @@ export default function FormModal({ open, handleClose, mode, selectedCar, modalK
 	};
 	const handleEdit = async (newForm) => {
 		try {
-			const res = await apiService.put(`/car/${selectedCar?._id}`, { ...newForm });
+			const res = await apiService.put(`/cars/${selectedCar?._id}`, { ...newForm });
 			refreshData();
 			console.log(res);
```
Comment (eatmoarrice) [inline src/components/FormModal.js]: Delete this console.log.

File: src/components/FormModal.js [hunk 5]
```diff
@@ -43,7 +43,7 @@ export default function FormModal({ open, handleClose, mode, selectedCar, modalK
 	};
 	const handleCreate = async (newForm) => {
 		try {
-			const res = await apiService.post('/car', { ...newForm });
+			const res = await apiService.post('/cars', { ...newForm });
 			refreshData();
 			console.log(res);
```
Comment (eatmoarrice) [inline src/components/FormModal.js:47]: Delete this console.log.

File: src/components/FormModal.js (hunk 1 above)
Comment (eatmoarrice) [inline src/components/FormModal.js]: Delete this console.log.

**Review by eatmoarrice — CHANGES_REQUESTED** [review]
In the future, please write meaningful commit messages.

PR description should at least include:
- WHY (you're missing this): Describe he problem with screenshots, texts, etc.
- WHAT: What you did to solve the issue, e.g. added a new dependency to the useEffect array, used `useCallback` to ..., etc. or something more general.

File: src/pages/HomePage.js (hunk 2 above)
Comment (krystalmai) [reply src/pages/HomePage.js]: in the existing code, getData() is also called elsewhere outside of the useEffect hook so I can't move the declaration inside useEffect, hence i resorted to useCallback() to avoid the missing dependency warning

File: src/components/FormModal.js (hunk 1 above)
Comment (krystalmai) [reply src/components/FormModal.js]: the why and what were briefly described in the pull request description, but missing screenshots. I'll find a way to include them and make the text more clear

**Review by eatmoarrice — APPROVED** [review]
